#!/bin/zsh

# This script is designed to automate the synchronization of multiple Git branches. It defines a set
# of parent branches and their corresponding child branches, then iterates through each parent-child
# relationship to ensure that changes in the parent branches are propagated to their child branches.
# This helps maintain consistency across the branches by rebasing and force-pushing updates.

typeset -A BRANCHES

BRANCHES=(
    [master]="unix windows"
    [unix]="linux darwin"
)

for parent_branch in ${(k)BRANCHES}; do
    if [[ $parent_branch == "master" ]]; then
        git checkout $parent_branch
        git pull origin $parent_branch
    fi
    for child_branch in ${(z)BRANCHES[$parent_branch]}; do
        git checkout $child_branch
        git rebase $parent_branch
        git push origin $child_branch --force-with-lease
    done
done
